const ProfileData = {
  Faculty: [
    {
      name: "Dr. Ebin Deni Raj",
      email: "ebindeniraj@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202195",
      linkedin: "https://www.linkedin.com/in/ebin-deni-raj-153b8742/",
      image: "ebindeniraj.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position: "Associate Dean (Academic Affairs)",
      research: [
        "Responsible AI",
        "Explainable & Interpretable AI",
        "Data Science",
      ],
    },

    {
      name: "Dr. Arun Cyril Jose",
      email: "aruncyril@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202159",
      linkedin: "https://www.linkedin.com/in/dr-arun-cyril-jose-a62a8299/",
      image: "aruncyril.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position: "Institute CVO",
      research: ["Privacy", "Security based Social Engineering"],
    },

    {
      name: "Dr. Gayathri G. R",
      email: "gayathri@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202184",
      linkedin: "https://www.linkedin.com/in/dr-gayathri-g-r-802781244/",
      image: "gayathri.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position: "Faculty In-Charge (Cultural Club,Social Media & Branding)",
      research: ["Cultural Studies", "Language Teaching"],
    },

    {
      name: "Dr. Jayakrushna Sahoo",
      email: "jsahoo@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202164",
      linkedin: "https://www.linkedin.com/in/jayakrushna-sahoo-14932232/",
      image: "jsahoo.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position: "HOD (Computer Science & Engineering-1)",
      research: ["Machine Learning", "Data Mining"],
    },

    {
      name: "Dr. Josit Mariya",
      email: "jositmariya@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202203",
      linkedin: "https://www.linkedin.com/in/josit-mariya-93ab3a253/",
      image: "jositmariya.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position:
        "Faculty In-Charge(Webservices & Public Relations),Nodal Officer, AISHE,Associate Faculty In-Charge (Training & Placement Cell)",
      research: ["Cultural Hegemony", "Sociological Studies"],
    },
    {
      name: "Divya Sindhu Lekha",
      email: "divyaslekha@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202161",
      linkedin: "https://www.linkedin.com/in/divyalekha/",
      image: "divyasindhulekha.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position:
        "Post Doc CUSAT, Ph.D. from University of Kerala, Awarded National Post-Doctoral Fellowship, SERB, DST, GOI, former employee HCL Technologies Ltd.",
      research: ["Graph Theory", "Network Science", "Algorithms"],
    },
  ],
  PhDScholars: [
    {
      name: "Jeena Thomas",
      linkedin: "https://www.linkedin.com/in/jeena-thomas-456149167/",
      image: "jeena.png",
      position: "Department of CSE",
    },
    {
      name: "Shahad P",
      linkedin: "",
      image: "shahad.png",
      position: "Department of CSE",
    },
    {
      name: "Ashly Ann Jo",
      linkedin: "https://www.linkedin.com/in/ashly-ann-jo-b18695145/",
      image: "ashly.png",
      position: "Department of CSE",
    },
    {
      name: "Remya Raveendran",
      linkedin: "https://www.linkedin.com/in/remya-raveendran-7293444a/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Mahesh Sasikumar",
      linkedin: "www.linkedin.com/in/mahesh-sasikumar-iiitk-4606192a3",
      image: "Mahesh_Sasikumar.png",
      position: "Department of CSE",
    },
    {
      name: "Akarsh Nair",
      linkedin: "https://www.linkedin.com/in/akarsh-k-nair-03298220b/",
      image: "akarsh.png",
      position: "Department of CSE",
    },
    {
      name: "Chinju John",
      linkedin: "https://www.linkedin.com/in/chinju-john-a95876b4/",
      image: "chinju.png",
      position: "Department of CSE",
    },
    {
      name: "Anitha Ambat",
      linkedin: "https://www.linkedin.com/in/anitha-ambat-198a36243",
      image: "Anitha_Ambat.png",
      position: "Department of CSE",
    },
    {
      name: "Ruchi Rani",
      linkedin: "https://www.linkedin.com/in/ruchi-rani-85873153/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Sreekala",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Renji S",
      linkedin: "https://www.linkedin.com/in/renji-s-157083253/",
      image: "Renji_S.png",
      position: "Department of CSE",
    },
    {
      name: "Akshaya Suresh",
      linkedin: "https://www.linkedin.com/in/akshaya-suresh-39a63b18a/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Sheema Madhusudhanan",
      linkedin: "https://www.linkedin.com/in/sheema-madhusudhanan-83410825b",
      image: "Sheema_Madhusudhanan.png",
      position: "Department of CSE",
    },
    {
      name: "Dhanya P",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Jisha Mariyam John",
      linkedin: "https://www.linkedin.com/in/jisha-mariyam-john-14575294/",
      image: "JISHA_MARIYAM_JOHN.png",
      position: "Department of CSE",
    },
    {
      name: "Neethu Krishna",
      linkedin: "https://www.linkedin.com/in/neethu-krishna-29b667235",
      image: "Neethu_Krishna.png",
      position: "Department of CSE",
    },
    {
      name: "Julie Sara Benny",
      linkedin: "https://www.linkedin.com/in/julie-sara-benny-b60698237/",
      image: "Julie Sara Benny.png",
      position: "Department of CSE",
    },
    {
      name: "Helena Thomas",
      linkedin: "www.linkedin.com/in/helena-thomas-b15081114",
      image: "Helena_Thomas.png",
      position: "Department of CSE",
    },
  ],
  MTech: [
    {
      name: "Ranjith R",
      linkedin: "https://www.linkedin.com/in/ranjith-r-3656aa10b/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Susmera Joseph",
      linkedin: "https://www.linkedin.com/in/susmera-joseph-769a3937/",
      image: "SUSMERA_JOSEPH.png",
      position: "Department of CSE",
    },
    {
      name: "Ijas AH",
      linkedin: "https://www.linkedin.com/in/ijas-ah/",
      image: "Ijas_A_H.png",
      position: "Department of CSE",
    },
    {
      name: "Selvaraj Mariyappan",
      linkedin: "https://www.linkedin.com/in/selvaraj-mariyappan-12629864/",
      image: "SELVARAJ_MARIYAPPAN.png",
      position: "Department of CSE",
    },
  ],
  UG: [
    {
      name: "Subodh Uniyal",
      linkedin: "https://www.linkedin.com/in/subodh7300/",
      image: "SUBODH_UNIYAL.png",
      position: "Department of CSE",
    },
    {
      name: "Maitri Deepak Savla",
      linkedin: "https://www.linkedin.com/in/maitri-savla-a5544b229",
      image: "MAITRI_DEEPAK_SAVLA.png",
      position: "Department of CSE",
    },
    {
      name: "Tushar K",
      linkedin: "https://www.linkedin.com/in/tushaar9560",
      image: "TUSHAAR.png",
      position: "Department of CSE",
    },
    {
      name: "Dhivyesh",
      linkedin: "https://www.linkedin.com/in/dhivyesh-rk/",
      image: "DHIVYESH_R_K.png",
      position: "Department of CSE",
    },
    {
      name: "Anish Reddy Konyala",
      linkedin: "https://linkedin.com/in/anish-reddy-konyala-9496ab229/",
      image: "KONYALA_ANISH_REDDY.png",
      position: "Department of CSE",
    },
    {
      name: "Kashyap Chandra",
      linkedin: "https://www.linkedin.com/in/kashyap-chandra-7a1132218",
      image: "kashyap_chandra.png",
      position: "Department of CSE",
    },
  ],
  Interns: [
    {
      name: "Angel Susan Vino",
      linkedin: "https://www.linkedin.com/in/angel-susan-vino-1920931b8/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Parvathy V Menon",
      linkedin: "https://www.linkedin.com/in/parvathy-menon-92a160218/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Sikha S",
      linkedin: "https://www.linkedin.com/in/sikha-s-43b2b2231/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Dhimant Morakhia",
      linkedin: "https://www.linkedin.com/in/dhimant-morakhia/",
      image: "",
      position: "Department of CSE",
    },
  ],
  Alumni: [
    {
      name: "Thiruthuvaraj Rajshekar",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Bhagya J",
      linkedin: "https://www.linkedin.com/in/bhagya-j-589237125",
      image: "Bhagya_J.png",
      position: "Department of CSE",
    },
    {
      name: "Amal Das",
      linkedin: "https://www.linkedin.com/in/amal-das-4006b482/",
      image: "Amal_Das.png",
      position: "Department of CSE",
    },
    {
      name: "Sai Tejashwin Eswarapu",
      linkedin: "https://www.linkedin.com/in/sai-tejashwin/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Yashwanth Deshaboina",
      linkedin: "https://www.linkedin.com/in/yashwanth-deshaboina-1799471b0/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Seshathri S",
      linkedin: "https://www.linkedin.com/in/seshathri-s-32a5281a5/",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Bhargawa P",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Nithin A",
      linkedin: "https://www.linkedin.com/in/nithin-a-19635520a",
      image: "A_Nithin.png",
      position: "Department of CSE",
    },
  ],
};

export default ProfileData;
