const ProfileData = {
  Faculty: [
    {
      name: "Dr. Ebin Deni Raj",
      email: "ebindeniraj@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202195",
      linkedin: "https://www.linkedin.com/in/ebin-deni-raj-153b8742/",
      image: "ebindeniraj.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position: "Associate Dean (Academic Affairs)",
      research: [
        "Responsible AI",
        "Explainable & Interpretable AI",
        "Data Science",
      ],
    },

    {
      name: "Dr. Arun Cyril Jose",
      email: "aruncyril@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202159",
      linkedin: "https://www.linkedin.com/in/dr-arun-cyril-jose-a62a8299/",
      image: "aruncyril.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position: "Institute CVO",
      research: ["Privacy", "Security based Social Engineering"],
    },

    {
      name: "Dr. Gayathri G. R",
      email: "gayathri@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202184",
      linkedin: "https://www.linkedin.com/in/dr-gayathri-g-r-802781244/",
      image: "gayathri.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position: "Faculty In-Charge (Cultural Club,Social Media & Branding)",
      research: ["Cultural Studies", "Language Teaching"],
    },

    {
      name: "Dr. Jayakrushna Sahoo",
      email: "jsahoo@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202164",
      linkedin: "https://www.linkedin.com/in/jayakrushna-sahoo-14932232/",
      image: "jsahoo.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position: "HOD (Computer Science & Engineering-1)",
      research: ["Machine Learning", "Data Mining"],
    },

    {
      name: "Dr. Josit Mariya",
      email: "jositmariya@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202203",
      linkedin: "https://www.linkedin.com/in/josit-mariya-93ab3a253/",
      image: "jositmariya.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position:
        "Faculty In-Charge(Webservices & Public Relations),Nodal Officer, AISHE,Associate Faculty In-Charge (Training & Placement Cell)",
      research: ["Cultural Hegemony", "Sociological Studies"],
    },
    {
      name: "Divya Sindhu Lekha",
      email: "divyaslekha@iiitkottayam.ac.in",
      phone: "+91 (0) 482-2202161",
      linkedin: "https://www.linkedin.com/in/divyalekha/",
      image: "divyasindhulekha.png",
      designation: "Faculty- IIIT KOTTAYAM",
      position:
        "Post Doc CUSAT, Ph.D. from University of Kerala, Awarded National Post-Doctoral Fellowship, SERB, DST, GOI, former employee HCL Technologies Ltd.",
      research: ["Graph Theory", "Network Science", "Algorithms"],
    },
  ],
  PhDScholars: [
    {
      name: "Jeena Thomas",
      linkedin: "",
      image: "jeena.png",
      position: "Department of CSE",
    },
    {
      name: "Shahad P",
      linkedin: "",
      image: "shahad.png",
      position: "Department of CSE",
    },
    {
      name: "Ashly Ann Jo",
      linkedin: "",
      image: "ashly.jpg",
      position: "Department of CSE",
    },
    {
      name: "Remya Raveendran",
      linkedin: "",
      image: "Remya_Raveendran.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Mahesh Sasikumar",
      linkedin: "",
      image: "Mahesh_Sasikumar.png",
      position: "Department of CSE",
    },
    {
      name: "Akarsh Nair",
      linkedin: "",
      image: "akarsh.png",
      position: "Department of CSE",
    },
    {
      name: "Chinju John",
      linkedin: "",
      image: "chinju.png",
      position: "Department of CSE",
    },
    {
      name: "Anitha Ambat",
      linkedin: "",
      image: "Anitha_Ambat.png",
      position: "Department of CSE",
    },
    {
      name: "Ruchi Rani",
      linkedin: "",
      image: "Ruchi_Rani.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Sreekala",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Renji R",
      linkedin: "",
      image: "Renji_S.png",
      position: "Department of CSE",
    },
    {
      name: "Akshaya Suresh",
      linkedin: "",
      image: "Akshaya_Suresh.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Sheema Madhusudhanan",
      linkedin: "",
      image: "Sheema_Madhusudhanan.png",
      position: "Department of CSE",
    },
    {
      name: "Dhanya P",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Jisha Mariyam John",
      linkedin: "",
      image: "JISHA_MARIYAM_JOHN.png",
      position: "Department of CSE",
    },
    {
      name: "Neethu Krishna",
      linkedin: "",
      image: "Neethu_Krishna.png",
      position: "Department of CSE",
    },
    {
      name: "Julie Sara Benny",
      linkedin: "",
      image: "Julie Sara Benny.png",
      position: "Department of CSE",
    },
    {
      name: "Helena Thomas",
      linkedin: "",
      image: "Helena_Thomas.png",
      position: "Department of CSE",
    },
  ],
  MTech: [
    {
      name: "Ranjith R",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Susmera Joseph",
      linkedin: "",
      image: "SUSMERA_JOSEPH.png",
      position: "Department of CSE",
    },
    {
      name: "Ijas AH",
      linkedin: "",
      image: "Ijas_A_H.png",
      position: "Department of CSE",
    },
    {
      name: "Selvaraj Mariyappan",
      linkedin: "",
      image: "SELVARAJ_MARIYAPPAN.png",
      position: "Department of CSE",
    },
  ],
  UG: [
    {
      name: "Subodh Uniyal",
      linkedin: "",
      image: "SUBODH_UNIYAL.png",
      position: "Department of CSE",
    },
    {
      name: "Maitri Deepak Savla",
      linkedin: "",
      image: "MAITRI_DEEPAK_SAVLA.png",
      position: "Department of CSE",
    },
    {
      name: "Tushar K",
      linkedin: "",
      image: "TUSHAAR.png",
      position: "Department of CSE",
    },
    {
      name: "Dhivyesh",
      linkedin: "",
      image: "DHIVYESH_R_K.png",
      position: "Department of CSE",
    },
    {
      name: "Anish Reddy Konyala",
      linkedin: "",
      image: "KONYALA_ANISH_REDDY.png",
      position: "Department of CSE",
    },
    {
      name: "Kashyap Chandra",
      linkedin: "",
      image: "kashyap_chandra.png",
      position: "Department of CSE",
    },
  ],
  Interns: [
    {
      name: "Angel Susan Vino",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Parvathy V Menon",
      linkedin: "",
      image: "Parvathy_V_Menon.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Sikha S",
      linkedin: "",
      image: "Sikha_S.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Dhimant Morakhia",
      linkedin: "",
      image: "Dhimant_Morakhia.jpeg",
      position: "Department of CSE",
    },
  ],
  Alumni: [
    {
      name: "Thiruthuvaraj Rajshekar ",
      linkedin: "",
      image: "raja.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Bhagya J",
      linkedin: "",
      image: "Bhagya_J.png",
      position: "Department of CSE",
    },
    {
      name: "Amal Das",
      linkedin: "",
      image: "Amal_Das.png",
      position: "Department of CSE",
    },
    {
      name: "Sai Tejashwin Eswarapu",
      linkedin: "",
      image: "Sai_Tejashwin_Eswarapu.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Yashwanth Deshaboina",
      linkedin: "",
      image: "Yashwanth_Deshaboina.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Seshathri S",
      linkedin: "",
      image: "Seshathri_S.jpeg",
      position: "Department of CSE",
    },
    {
      name: "Bhargawa P",
      linkedin: "",
      image: "",
      position: "Department of CSE",
    },
    {
      name: "Nithin A",
      linkedin: "",
      image: "A_Nithin.png",
      position: "Department of CSE",
    },
  ],
};

export default ProfileData;